import type {
  Artist,
  GalleryItem,
  Booking,
  InventoryItem,
  Transaction,
  ArtistPayout,
  Testimonial,
  FAQItem,
} from './types';

export const artists: Artist[] = [
  {
    id: 'a1',
    name: 'Raven Vex',
    title: 'Founder & Master Artist',
    specialty: 'Blackwork',
    bio: 'Fifteen years of carving darkness into skin. Raven specializes in heavy blackwork and sacred geometry, turning the body into a living canvas of shadow and contrast.',
    image: 'https://images.pexels.com/photos/4125532/pexels-photo-4125532.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    experienceYears: 15,
    instagram: '@ravenvex.ink',
    rating: 4.9,
    sessionsCompleted: 1240,
  },
  {
    id: 'a2',
    name: 'Mira Saiki',
    title: 'Realism & Portrait Specialist',
    specialty: 'Realism',
    bio: 'Mira brings photographs to life with photorealistic detail. Her portraits and nature pieces have earned international recognition across three continents.',
    image: 'https://images.pexels.com/photos/4125531/pexels-photo-4125531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    experienceYears: 11,
    instagram: '@mirasaiki.art',
    rating: 5.0,
    sessionsCompleted: 870,
  },
  {
    id: 'a3',
    name: 'Kai Okonkwo',
    title: 'Fine Line & Geometric',
    specialty: 'Fine Line',
    bio: 'Precision is Kai\'s religion. Delicate single-needle fine line work and mathematically precise geometric patterns define his minimalist portfolio.',
    image: 'https://images.pexels.com/photos/4655712/pexels-photo-4655712.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    experienceYears: 8,
    instagram: '@kai.finelinework',
    rating: 4.8,
    sessionsCompleted: 640,
  },
  {
    id: 'a4',
    name: 'Luna Ashford',
    title: 'Traditional & Japanese',
    specialty: 'Japanese',
    bio: 'Bold lines, timeless imagery. Luna blends classic American traditional with Japanese irezumi, creating pieces built to age gracefully for decades.',
    image: 'https://images.pexels.com/photos/6024213/pexels-photo-6024213.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    experienceYears: 13,
    instagram: '@luna.ashford.tattoo',
    rating: 4.9,
    sessionsCompleted: 1020,
  },
];

export const gallery: GalleryItem[] = [
  {
    id: 'g1',
    title: 'Eclipse Mandala',
    artistId: 'a1',
    style: 'Blackwork',
    image: 'https://images.pexels.com/photos/14565781/pexels-photo-14565781.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Full Sleeve',
    hours: 32,
  },
  {
    id: 'g2',
    title: 'Lotus Reverie',
    artistId: 'a2',
    style: 'Realism',
    image: 'https://images.pexels.com/photos/29251831/pexels-photo-29251831.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Upper Arm',
    hours: 18,
  },
  {
    id: 'g3',
    title: 'Sacred Geometry',
    artistId: 'a3',
    style: 'Geometric',
    image: 'https://images.pexels.com/photos/28991523/pexels-photo-28991523.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Forearm',
    hours: 9,
  },
  {
    id: 'g4',
    title: 'Koi Ascension',
    artistId: 'a4',
    style: 'Japanese',
    image: 'https://images.pexels.com/photos/2126124/pexels-photo-2126124.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Back',
    hours: 40,
  },
  {
    id: 'g5',
    title: 'Whispered Lines',
    artistId: 'a3',
    style: 'Fine Line',
    image: 'https://images.pexels.com/photos/27411379/pexels-photo-27411379.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Forearm',
    hours: 6,
  },
  {
    id: 'g6',
    title: 'Dark Bloom',
    artistId: 'a1',
    style: 'Blackwork',
    image: 'https://images.pexels.com/photos/13304597/pexels-photo-13304597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Back',
    hours: 28,
  },
  {
    id: 'g7',
    title: 'Eternal Portrait',
    artistId: 'a2',
    style: 'Portrait',
    image: 'https://images.pexels.com/photos/30235783/pexels-photo-30235783.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Chest',
    hours: 22,
  },
  {
    id: 'g8',
    title: 'Iron Tradition',
    artistId: 'a4',
    style: 'Traditional',
    image: 'https://images.pexels.com/photos/17402466/pexels-photo-17402466.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    placement: 'Hand',
    hours: 4,
  },
];

export const bookings: Booking[] = [
  {
    id: 'BK-2401',
    clientName: 'Arjun Mehta',
    email: 'arjun.m@gmail.com',
    phone: '+91 98200 11234',
    artistId: 'a1',
    artistName: 'Raven Vex',
    date: '2026-09-02',
    time: '11:00',
    placement: 'Full Sleeve',
    size: 'Full Piece (12"+)',
    style: 'Blackwork',
    description: 'Full sleeve blackwork mandala with geometric transitions. 3 sessions estimated.',
    depositPaid: true,
    depositAmount: 2000,
    estimatedCost: 45000,
    status: 'Confirmed',
    createdAt: '2026-08-20',
  },
  {
    id: 'BK-2402',
    clientName: 'Priya Nair',
    email: 'priya.nair@outlook.com',
    phone: '+91 99873 45621',
    artistId: 'a2',
    artistName: 'Mira Saiki',
    date: '2026-09-04',
    time: '14:30',
    placement: 'Ribs',
    size: 'Large (6"-12")',
    style: 'Realism',
    description: 'Photorealistic lotus bloom along ribcage. Single session.',
    depositPaid: true,
    depositAmount: 2000,
    estimatedCost: 28000,
    status: 'Confirmed',
    createdAt: '2026-08-22',
  },
  {
    id: 'BK-2403',
    clientName: 'Daniel Cohen',
    email: 'd.cohen@gmail.com',
    phone: '+91 90011 22334',
    artistId: 'a3',
    artistName: 'Kai Okonkwo',
    date: '2026-08-30',
    time: '16:00',
    placement: 'Forearm',
    size: 'Small (< 3")',
    style: 'Fine Line',
    description: 'Minimal fine line botanical sprig. Quick session.',
    depositPaid: true,
    depositAmount: 2000,
    estimatedCost: 6500,
    status: 'Completed',
    createdAt: '2026-08-15',
  },
  {
    id: 'BK-2404',
    clientName: 'Sara Khan',
    email: 'sara.k@gmail.com',
    phone: '+91 98765 43210',
    artistId: 'a4',
    artistName: 'Luna Ashford',
    date: '2026-09-08',
    time: '10:00',
    placement: 'Back',
    size: 'Full Piece (12"+)',
    style: 'Japanese',
    description: 'Japanese koi and dragon full back piece. Multi-session epic.',
    depositPaid: true,
    depositAmount: 2000,
    estimatedCost: 62000,
    status: 'In Progress',
    createdAt: '2026-08-18',
  },
  {
    id: 'BK-2405',
    clientName: 'Vikram Raj',
    email: 'vikram.r@gmail.com',
    phone: '+91 91234 56789',
    artistId: 'a1',
    artistName: 'Raven Vex',
    date: '2026-09-12',
    time: '13:00',
    placement: 'Chest',
    size: 'Large (6"-12")',
    style: 'Blackwork',
    description: 'Ornamental chest blackwork with dotwork shading.',
    depositPaid: false,
    depositAmount: 2000,
    estimatedCost: 32000,
    status: 'Confirmed',
    createdAt: '2026-08-25',
  },
  {
    id: 'BK-2406',
    clientName: 'Ananya Iyer',
    email: 'ananya.i@gmail.com',
    phone: '+91 99665 54321',
    artistId: 'a2',
    artistName: 'Mira Saiki',
    date: '2026-09-15',
    time: '15:30',
    placement: 'Upper Arm',
    size: 'Medium (3"-6")',
    style: 'Portrait',
    description: 'Pet portrait realism piece on upper arm.',
    depositPaid: true,
    depositAmount: 2000,
    estimatedCost: 18000,
    status: 'Confirmed',
    createdAt: '2026-08-24',
  },
  {
    id: 'BK-2407',
    clientName: 'Rohit Sharma',
    email: 'rohit.s@gmail.com',
    phone: '+91 98111 33445',
    artistId: 'a3',
    artistName: 'Kai Okonkwo',
    date: '2026-08-28',
    time: '12:00',
    placement: 'Neck',
    size: 'Small (< 3")',
    style: 'Geometric',
    description: 'Small geometric triangle composition behind ear.',
    depositPaid: true,
    depositAmount: 2000,
    estimatedCost: 5500,
    status: 'Completed',
    createdAt: '2026-08-10',
  },
  {
    id: 'BK-2408',
    clientName: 'Meera Kapoor',
    email: 'meera.k@gmail.com',
    phone: '+91 97445 88990',
    artistId: 'a4',
    artistName: 'Luna Ashford',
    date: '2026-09-20',
    time: '11:30',
    placement: 'Thigh',
    size: 'Large (6"-12")',
    style: 'Traditional',
    description: 'Traditional rose and dagger thigh piece.',
    depositPaid: false,
    depositAmount: 2000,
    estimatedCost: 24000,
    status: 'Cancelled',
    createdAt: '2026-08-19',
  },
];

export const inventory: InventoryItem[] = [
  { id: 'inv1', name: 'Bugpin Magnum Needles (5M1)', category: 'Needle', stock: 42, minStock: 20, unit: 'pcs', supplier: 'Cheyenne Supply', unitCost: 320 },
  { id: 'inv2', name: 'Round Liner Needles (3RL)', category: 'Needle', stock: 8, minStock: 25, unit: 'pcs', supplier: 'Kuro Sumi', unitCost: 180 },
  { id: 'inv3', name: 'Dynamic Black Ink (12oz)', category: 'Ink', stock: 15, minStock: 8, unit: 'bottles', supplier: 'Dynamic Ink Co.', unitCost: 1450 },
  { id: 'inv4', name: 'Kuro Sumi Outlining Ink (10oz)', category: 'Ink', stock: 3, minStock: 6, unit: 'bottles', supplier: 'Kuro Sumi', unitCost: 1200 },
  { id: 'inv5', name: 'Intenze White Snow Ink (3oz)', category: 'Ink', stock: 11, minStock: 5, unit: 'bottles', supplier: 'Intenze Supply', unitCost: 850 },
  { id: 'inv6', name: 'Nitrile Gloves (Medium)', category: 'Glove', stock: 240, minStock: 100, unit: 'pcs', supplier: 'MedSupply India', unitCost: 12 },
  { id: 'inv7', name: 'Nitrile Gloves (Large)', category: 'Glove', stock: 18, minStock: 100, unit: 'pcs', supplier: 'MedSupply India', unitCost: 12 },
  { id: 'inv8', name: 'Aquafor Aftercare Ointment (3oz)', category: 'Aftercare', stock: 36, minStock: 15, unit: 'tubes', supplier: 'TattooCare Direct', unitCost: 240 },
  { id: 'inv9', name: 'Second Skin Film (6"x8")', category: 'Aftercare', stock: 4, minStock: 20, unit: 'sheets', supplier: 'TattooCare Direct', unitCost: 95 },
  { id: 'inv10', name: 'Tattoo Machine Cartridges - Box of 20', category: 'Equipment', stock: 7, minStock: 10, unit: 'boxes', supplier: 'Cheyenne Supply', unitCost: 4200 },
  { id: 'inv11', name: 'Ink Cups (Disposable)', category: 'Equipment', stock: 500, minStock: 200, unit: 'pcs', supplier: 'BulkTattoo Supply', unitCost: 3 },
  { id: 'inv12', name: 'Green Soap Concentrate (16oz)', category: 'Aftercare', stock: 9, minStock: 6, unit: 'bottles', supplier: 'MedSupply India', unitCost: 380 },
];

export const transactions: Transaction[] = [
  { id: 't1', date: '2026-08-28', description: 'Session — BK-2407 Geometric Neck', category: 'Revenue', amount: 5500, bookingId: 'BK-2407' },
  { id: 't2', date: '2026-08-30', description: 'Session — BK-2403 Fine Line Forearm', category: 'Revenue', amount: 6500, bookingId: 'BK-2403' },
  { id: 't3', date: '2026-08-15', description: 'Needle Restock — Cheyenne Supply', category: 'Expense', amount: 13440 },
  { id: 't4', date: '2026-08-18', description: 'Ink Restock — Dynamic Ink Co.', category: 'Expense', amount: 14500 },
  { id: 't5', date: '2026-08-20', description: 'Deposit — BK-2401 Full Sleeve', category: 'Revenue', amount: 2000, bookingId: 'BK-2401' },
  { id: 't6', date: '2026-08-22', description: 'Deposit — BK-2402 Realism Ribs', category: 'Revenue', amount: 2000, bookingId: 'BK-2402' },
  { id: 't7', date: '2026-08-24', description: 'Deposit — BK-2406 Portrait Upper Arm', category: 'Revenue', amount: 2000, bookingId: 'BK-2406' },
  { id: 't8', date: '2026-08-12', description: 'Glove Restock — MedSupply India', category: 'Expense', amount: 2880 },
  { id: 't9', date: '2026-08-05', description: 'Aftercare Restock — TattooCare Direct', category: 'Expense', amount: 8640 },
  { id: 't10', date: '2026-08-01', description: 'Studio Rent — August', category: 'Expense', amount: 45000 },
  { id: 't11', date: '2026-08-03', description: 'Utilities & Internet', category: 'Expense', amount: 6200 },
  { id: 't12', date: '2026-08-07', description: 'Session — Walk-in Touch-up', category: 'Revenue', amount: 3500 },
];

export const artistPayouts: ArtistPayout[] = [
  { id: 'p1', artistId: 'a1', artistName: 'Raven Vex', period: 'August 2026', grossRevenue: 86000, studioShare: 34400, artistShare: 51600, status: 'Pending' },
  { id: 'p2', artistId: 'a2', artistName: 'Mira Saiki', period: 'August 2026', grossRevenue: 64000, studioShare: 25600, artistShare: 38400, status: 'Pending' },
  { id: 'p3', artistId: 'a3', artistName: 'Kai Okonkwo', period: 'August 2026', grossRevenue: 38000, studioShare: 15200, artistShare: 22800, status: 'Paid' },
  { id: 'p4', artistId: 'a4', artistName: 'Luna Ashford', period: 'August 2026', grossRevenue: 92000, studioShare: 36800, artistShare: 55200, status: 'Pending' },
];

export const testimonials: Testimonial[] = [
  {
    id: 'ts1',
    name: 'Arjun Mehta',
    rating: 5,
    text: 'Raven turned my vision into something I couldn\'t have imagined. The detail in the blackwork is unreal. Three sessions and every minute was worth it.',
    tattoo: 'Full Sleeve Blackwork',
    date: 'August 2026',
  },
  {
    id: 'ts2',
    name: 'Sara Khan',
    rating: 5,
    text: 'The studio is immaculate, the artists are obsessive about hygiene, and Luna\'s Japanese work is museum quality. I\'ve found my forever studio.',
    tattoo: 'Full Back Japanese',
    date: 'July 2026',
  },
  {
    id: 'ts3',
    name: 'Daniel Cohen',
    rating: 5,
    text: 'Kai\'s fine line work is surgical. The try-on tool helped me decide on placement before committing. The whole experience felt premium from start to finish.',
    tattoo: 'Fine Line Forearm',
    date: 'August 2026',
  },
  {
    id: 'ts4',
    name: 'Priya Nair',
    rating: 5,
    text: 'Mira\'s realism is genuinely photographic. People don\'t believe my lotus tattoo is real ink. The booking process was seamless and the deposit system made it feel serious.',
    tattoo: 'Realism Ribcage',
    date: 'June 2026',
  },
];

export const faqs: FAQItem[] = [
  {
    id: 'f1',
    question: 'Is the ₹2,000 deposit refundable?',
    answer: 'No. The deposit secures your appointment slot and covers artist preparation time. It is non-refundable but is adjusted against your final session cost.',
  },
  {
    id: 'f2',
    question: 'How do I prepare for my first session?',
    answer: 'Eat a full meal 1-2 hours before, stay hydrated, avoid alcohol for 24 hours prior, and wear comfortable clothing that allows easy access to the tattoo area. Moisturize your skin for a few days leading up to the session.',
  },
  {
    id: 'f3',
    question: 'How long does a tattoo take to heal?',
    answer: 'Surface healing takes 2-3 weeks. Full dermal healing takes 4-6 weeks. We provide a complete aftercare kit and instructions with every session.',
  },
  {
    id: 'f4',
    question: 'Can I see how a design looks before committing?',
    answer: 'Yes. Our Smart Try-On tool lets you upload a photo of your skin and a design image to preview the placement and scale using realistic blending — no AI or backend required.',
  },
  {
    id: 'f5',
    question: 'Do you do cover-ups?',
    answer: 'Absolutely. Book a consultation and bring your existing tattoo. Our artists will assess it and design a piece that transforms it into something new.',
  },
  {
    id: 'f6',
    question: 'What styles do your artists specialize in?',
    answer: 'Each artist has a specialty: Raven (Blackwork), Mira (Realism & Portraits), Kai (Fine Line & Geometric), and Luna (Traditional & Japanese). You can choose your artist during booking.',
  },
];

export const placementOptions: { label: string; icon: string }[] = [
  { label: 'Forearm', icon: ' forearm' },
  { label: 'Upper Arm', icon: ' upper arm' },
  { label: 'Back', icon: ' back' },
  { label: 'Chest', icon: ' chest' },
  { label: 'Calf', icon: ' calf' },
  { label: 'Thigh', icon: ' thigh' },
  { label: 'Ribs', icon: ' ribs' },
  { label: 'Neck', icon: ' neck' },
  { label: 'Hand', icon: ' hand' },
  { label: 'Full Sleeve', icon: ' full sleeve' },
];

export const sizeOptions = [
  'Small (< 3")',
  'Medium (3"-6")',
  'Large (6"-12")',
  'Full Piece (12"+)',
] as const;

export const styleOptions = [
  'Blackwork',
  'Realism',
  'Traditional',
  'Fine Line',
  'Geometric',
  'Japanese',
  'Portrait',
  'Custom',
] as const;

export const timeSlots = [
  '10:00', '11:00', '12:00', '13:00', '14:30', '15:30', '16:00', '17:00',
];
